
cerad_app__welcome:
    path: /welcome
    defaults:
        _model:      cerad_app__projects_model_factory
        _controller: cerad_app__welcome_controller:action
        _template: '@CeradApp/Welcome/WelcomeIndex.html.twig'
        
cerad_app__home:
    path: /home
    defaults:
        _userPerson: redirect if not found
        _model:      cerad_app__projects_model_factory
        _controller: cerad_app__home_controller:action
        _view:       cerad_app__home_view
        _template: '@CeradApp/Home/HomeIndex.html.twig'


cerad_app__userinfo:
    path: /userinfo
    defaults:
        _controller: cerad_app__userinfo_controller:action
        _userPerson: redirect if not found
        _template: '@CeradApp/UserInfo/ROLEIndex.html.twig'
        
cerad_app__index:
    path:  /
    defaults:
        _controller: cerad_app__welcome_controller:action
        _model:      cerad_app__welcome_model_factory
        _template: '@CeradApp/Welcome/WelcomeIndex.html.twig'
        
# ==================================================
# A ProjectPerson will have Project Person PersonPlan PersonFed

cerad_person__project_person__register:
    path:  /project/{_project}/person/{_person}/register
    defaults:
        _role:       ROLE_USER
        _model:      cerad_person__project_person_model_factory
        _form:       cerad_person__project_person__register_form_factory
        _controller: cerad_person__project_person__register_controller:action
        _template: '@CeradApp/ProjectPerson/Register/RegisterIndex.html.twig'
        _redirect:   cerad_app__home
  