     
key:        USSF_AL_HFCClassic_Spring2014
arbiter:    ALYS_SOCCER_HFCCLASSIC_SPRING2014
slug:       Classic2014
slugPrefix: Classic
role:       Tournament
    
fed:     USSF
fedOrg:  USSF_AL
fedRole: USSFC
                
name:    HFC Classic 2014
desc:    USSF HFC Classic 2014 - Huntsville, Alabama - April 4,5,6
    
   #general_url:  'http://www.huntsvillefc.org/springclassic/'
   #register_url: 'http://zayso.org/arbiter/tourn/opencup'
    
status:    Active
verified:  Yes
                
season:    Spring2014
sport:     Soccer
domain:    ALYS
domainSub: HFC Classic
                                
assignor:
  name:   Art Hundiak
  email:  ahundiak@gmail.com
  phone:  256.457.5943
  submit: Emails your application to Art Hundiak and yourself.
  prefix: Classic
  bcc:    { name: Art Hundiak, email: ahundiak@gmail.com }
  
dates:
  - { date: '2014-04-04', label: Fri, lodging: true,  search: true, avail: 5PM Kickoff }
  - { date: '2014-04-05', label: Sat, lodging: true,  search: true, avail: AllDay }
  - { date: '2014-04-06', label: Sun, lodging: false, search: true, avail: AllDay }
      
plan:
  refereeLevel:       ~                                   
  comfortLevelCenter: ~             
  comfortLevelAssist: ~
                        
  requestAssessment: ~

  lodging: ~
  lodgingWith:   ~
    
  travelingWith: ~
  travelingFrom: ~
                    
  teamClubAffilation: ~            
  teamClubName: ~
                             
  availability: ~
                            
  notes: ~
