key:        USSF_AL_HFCClassic_Spring2015
arbiter:    ALYS_SOCCER_HFCCLASSIC_FALL2015
slug:       Classic2015
slugPrefix: Classic
role:       Tournament
    
fed:     USSF
fedOrg:  USSF_AL
fedRole: USSFC
                
name:   "HFC Classic 2015"
desc:   "USSF HFC Classic 2015 - Huntsville, Alabama - April 24, 25, 26"
    
   #general_url:  'http://www.huntsvillefc.org/springclassic/'
   #register_url: 'http://zayso.org/arbiter/tourn/opencup'
    
status:    Active
verified:  Yes
                
season:    Spring2015
sport:     Soccer
domain:    ALYS
domainSub: HFC Classic
                                
assignor:
  name:   Andy J Dye II
  email:  andydye2@msn.com
  phone:  256.230.5425
  submit: Emails your application to Andy Dye and yourself.
  prefix: Classic
  bcc:    { name: Art Hundiak, email: ahundiak@gmail.com }
  
dates:
  - { date: '2015-04-24', label: Fri, lodging: true,  search: true, avail: 5PM Kickoff }
  - { date: '2015-04-25', label: Sat, lodging: true,  search: true, avail: AllDay }
  - { date: '2015-04-26', label: Sun, lodging: false, search: true, avail: AllDay }
      
plan:
  refereeLevel:       ~                                   
  comfortLevelCenter: ~             
  comfortLevelAssist: ~
                        
  requestAssessment: ~

  lodging: ~
  lodgingWith:   ~
    
  travelingWith: ~
  travelingFrom: ~
                    
  teamClubAffilation: ~            
  teamClubName: ~
                             
  availability: ~
                            
  notes: ~
