
cerad_app__routing_1:
    resource: "@CeradAppBundle/Resources/config/routing1.yml"
    prefix:   /
    
cerad_user_routing:
    resource: "@CeradUserBundle/Resources/config/routing.yml"
    prefix:   /
    
cerad_game_routing:
    resource: "@CeradGameBundle/Resources/config/routing.yml"
    prefix:   /
    
cerad_app__routing_2:
    resource: "@CeradAppBundle/Resources/config/routing2.yml"
    prefix:   /

